package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.id
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private String authorityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.is_used
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private Byte isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.gmt_create
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.gmt_modified
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.id
     *
     * @return the value of authority.id
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.id
     *
     * @param id the value for authority.id
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.name
     *
     * @return the value of authority.name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.name
     *
     * @param name the value for authority.name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_name
     *
     * @return the value of authority.authority_name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_name
     *
     * @param authorityName the value for authority.authority_name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.is_used
     *
     * @return the value of authority.is_used
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public Byte getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.is_used
     *
     * @param isUsed the value for authority.is_used
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setIsUsed(Byte isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.gmt_create
     *
     * @return the value of authority.gmt_create
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.gmt_create
     *
     * @param gmtCreate the value for authority.gmt_create
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.gmt_modified
     *
     * @return the value of authority.gmt_modified
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.gmt_modified
     *
     * @param gmtModified the value for authority.gmt_modified
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}