package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class AuthorityPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_permission.id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_permission.authority_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Integer authorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_permission.permission_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_permission.is_used
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Boolean isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_permission.gmt_create
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_permission.gmt_modified
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_permission.id
     *
     * @return the value of authority_permission.id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_permission.id
     *
     * @param id the value for authority_permission.id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_permission.authority_id
     *
     * @return the value of authority_permission.authority_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_permission.authority_id
     *
     * @param authorityId the value for authority_permission.authority_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_permission.permission_id
     *
     * @return the value of authority_permission.permission_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_permission.permission_id
     *
     * @param permissionId the value for authority_permission.permission_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_permission.is_used
     *
     * @return the value of authority_permission.is_used
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Boolean getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_permission.is_used
     *
     * @param isUsed the value for authority_permission.is_used
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setIsUsed(Boolean isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_permission.gmt_create
     *
     * @return the value of authority_permission.gmt_create
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_permission.gmt_create
     *
     * @param gmtCreate the value for authority_permission.gmt_create
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_permission.gmt_modified
     *
     * @return the value of authority_permission.gmt_modified
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority_permission.gmt_modified
     *
     * @param gmtModified the value for authority_permission.gmt_modified
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}