package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class ComAuditReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_audit_report.id
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_audit_report.report_template_id
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    private Long reportTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_audit_report.cominfo_id
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    private Long cominfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_audit_report.gmt_create
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_audit_report.gmt_modified
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_audit_report.id
     *
     * @return the value of com_audit_report.id
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_audit_report.id
     *
     * @param id the value for com_audit_report.id
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_audit_report.report_template_id
     *
     * @return the value of com_audit_report.report_template_id
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public Long getReportTemplateId() {
        return reportTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_audit_report.report_template_id
     *
     * @param reportTemplateId the value for com_audit_report.report_template_id
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public void setReportTemplateId(Long reportTemplateId) {
        this.reportTemplateId = reportTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_audit_report.cominfo_id
     *
     * @return the value of com_audit_report.cominfo_id
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public Long getCominfoId() {
        return cominfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_audit_report.cominfo_id
     *
     * @param cominfoId the value for com_audit_report.cominfo_id
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public void setCominfoId(Long cominfoId) {
        this.cominfoId = cominfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_audit_report.gmt_create
     *
     * @return the value of com_audit_report.gmt_create
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_audit_report.gmt_create
     *
     * @param gmtCreate the value for com_audit_report.gmt_create
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_audit_report.gmt_modified
     *
     * @return the value of com_audit_report.gmt_modified
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_audit_report.gmt_modified
     *
     * @param gmtModified the value for com_audit_report.gmt_modified
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}