package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class ComInfoAppendix {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.id
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_delegat
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comDelegat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_reporttype
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comReporttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_createyear
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comCreateyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_createmonth
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comCreatemonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_statisticsorg
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comStatisticsorg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regareacode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegareacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_address_xiang
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comAddressXiang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regaddr_sheng
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegaddrSheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regaddr_di
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegaddrDi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regaddr_xian
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegaddrXian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regaddr_xiang
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegaddrXiang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regaddr_jie
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegaddrJie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regaddr_she
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegaddrShe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_fax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_email
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_http
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comHttp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_zipcode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comZipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_orglevel_bus
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comOrglevelBus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regcode_bus
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegcodeBus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_orglevel_form
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comOrglevelForm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regcode_form
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegcodeForm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_orglevel_civil
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comOrglevelCivil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regcode_civil
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegcodeCivil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_orglevel_nattax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comOrglevelNattax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regcode_nattax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegcodeNattax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_orglevel_tax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comOrglevelTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regcode_tax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegcodeTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_orglevel_oth
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comOrglevelOth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regcode_oth
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegcodeOth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_stock
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_subrel
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comSubrel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_impaccclass
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comImpaccclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_isimprule
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comIsimprule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_comclass
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comComclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_delcomcode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comDelcomcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_delcomname
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comDelcomname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_delcomaddr
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comDelcomaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_delcomareacode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comDelcomareacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_industrycount
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private Double comIndustrycount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_comscale
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comComscale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_citycode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comCitycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regcitycode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegcitycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_telext
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comTelext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_faxext
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comFaxext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_zone
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comZone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_tel
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_mobile
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_industrytype
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comIndustrytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_comprincipal
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comComprincipal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_staprincipal
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comStaprincipal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_fillperson
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comFillperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_contacttel
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comContacttel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_adddate
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private Date comAdddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_groupid
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private Double comGroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_imgurl
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_status
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private Double comStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_apply
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comApply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_reply
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comReply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_industry
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_address_sheng
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comAddressSheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_address_di
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comAddressDi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_address_xian
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comAddressXian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_address_jie
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comAddressJie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_address_she
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comAddressShe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_address
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_regaddr
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comRegaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.com_loc_areacode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private String comLocAreacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.gmt_create
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo_appendix.gmt_modified
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.id
     *
     * @return the value of cominfo_appendix.id
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.id
     *
     * @param id the value for cominfo_appendix.id
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_delegat
     *
     * @return the value of cominfo_appendix.com_delegat
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComDelegat() {
        return comDelegat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_delegat
     *
     * @param comDelegat the value for cominfo_appendix.com_delegat
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComDelegat(String comDelegat) {
        this.comDelegat = comDelegat == null ? null : comDelegat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_reporttype
     *
     * @return the value of cominfo_appendix.com_reporttype
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComReporttype() {
        return comReporttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_reporttype
     *
     * @param comReporttype the value for cominfo_appendix.com_reporttype
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComReporttype(String comReporttype) {
        this.comReporttype = comReporttype == null ? null : comReporttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_createyear
     *
     * @return the value of cominfo_appendix.com_createyear
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComCreateyear() {
        return comCreateyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_createyear
     *
     * @param comCreateyear the value for cominfo_appendix.com_createyear
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComCreateyear(String comCreateyear) {
        this.comCreateyear = comCreateyear == null ? null : comCreateyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_createmonth
     *
     * @return the value of cominfo_appendix.com_createmonth
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComCreatemonth() {
        return comCreatemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_createmonth
     *
     * @param comCreatemonth the value for cominfo_appendix.com_createmonth
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComCreatemonth(String comCreatemonth) {
        this.comCreatemonth = comCreatemonth == null ? null : comCreatemonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_statisticsorg
     *
     * @return the value of cominfo_appendix.com_statisticsorg
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComStatisticsorg() {
        return comStatisticsorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_statisticsorg
     *
     * @param comStatisticsorg the value for cominfo_appendix.com_statisticsorg
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComStatisticsorg(String comStatisticsorg) {
        this.comStatisticsorg = comStatisticsorg == null ? null : comStatisticsorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regareacode
     *
     * @return the value of cominfo_appendix.com_regareacode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegareacode() {
        return comRegareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regareacode
     *
     * @param comRegareacode the value for cominfo_appendix.com_regareacode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegareacode(String comRegareacode) {
        this.comRegareacode = comRegareacode == null ? null : comRegareacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_address_xiang
     *
     * @return the value of cominfo_appendix.com_address_xiang
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComAddressXiang() {
        return comAddressXiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_address_xiang
     *
     * @param comAddressXiang the value for cominfo_appendix.com_address_xiang
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComAddressXiang(String comAddressXiang) {
        this.comAddressXiang = comAddressXiang == null ? null : comAddressXiang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regaddr_sheng
     *
     * @return the value of cominfo_appendix.com_regaddr_sheng
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegaddrSheng() {
        return comRegaddrSheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regaddr_sheng
     *
     * @param comRegaddrSheng the value for cominfo_appendix.com_regaddr_sheng
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegaddrSheng(String comRegaddrSheng) {
        this.comRegaddrSheng = comRegaddrSheng == null ? null : comRegaddrSheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regaddr_di
     *
     * @return the value of cominfo_appendix.com_regaddr_di
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegaddrDi() {
        return comRegaddrDi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regaddr_di
     *
     * @param comRegaddrDi the value for cominfo_appendix.com_regaddr_di
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegaddrDi(String comRegaddrDi) {
        this.comRegaddrDi = comRegaddrDi == null ? null : comRegaddrDi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regaddr_xian
     *
     * @return the value of cominfo_appendix.com_regaddr_xian
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegaddrXian() {
        return comRegaddrXian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regaddr_xian
     *
     * @param comRegaddrXian the value for cominfo_appendix.com_regaddr_xian
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegaddrXian(String comRegaddrXian) {
        this.comRegaddrXian = comRegaddrXian == null ? null : comRegaddrXian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regaddr_xiang
     *
     * @return the value of cominfo_appendix.com_regaddr_xiang
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegaddrXiang() {
        return comRegaddrXiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regaddr_xiang
     *
     * @param comRegaddrXiang the value for cominfo_appendix.com_regaddr_xiang
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegaddrXiang(String comRegaddrXiang) {
        this.comRegaddrXiang = comRegaddrXiang == null ? null : comRegaddrXiang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regaddr_jie
     *
     * @return the value of cominfo_appendix.com_regaddr_jie
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegaddrJie() {
        return comRegaddrJie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regaddr_jie
     *
     * @param comRegaddrJie the value for cominfo_appendix.com_regaddr_jie
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegaddrJie(String comRegaddrJie) {
        this.comRegaddrJie = comRegaddrJie == null ? null : comRegaddrJie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regaddr_she
     *
     * @return the value of cominfo_appendix.com_regaddr_she
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegaddrShe() {
        return comRegaddrShe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regaddr_she
     *
     * @param comRegaddrShe the value for cominfo_appendix.com_regaddr_she
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegaddrShe(String comRegaddrShe) {
        this.comRegaddrShe = comRegaddrShe == null ? null : comRegaddrShe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_fax
     *
     * @return the value of cominfo_appendix.com_fax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComFax() {
        return comFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_fax
     *
     * @param comFax the value for cominfo_appendix.com_fax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComFax(String comFax) {
        this.comFax = comFax == null ? null : comFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_email
     *
     * @return the value of cominfo_appendix.com_email
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComEmail() {
        return comEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_email
     *
     * @param comEmail the value for cominfo_appendix.com_email
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComEmail(String comEmail) {
        this.comEmail = comEmail == null ? null : comEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_http
     *
     * @return the value of cominfo_appendix.com_http
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComHttp() {
        return comHttp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_http
     *
     * @param comHttp the value for cominfo_appendix.com_http
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComHttp(String comHttp) {
        this.comHttp = comHttp == null ? null : comHttp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_zipcode
     *
     * @return the value of cominfo_appendix.com_zipcode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComZipcode() {
        return comZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_zipcode
     *
     * @param comZipcode the value for cominfo_appendix.com_zipcode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComZipcode(String comZipcode) {
        this.comZipcode = comZipcode == null ? null : comZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_orglevel_bus
     *
     * @return the value of cominfo_appendix.com_orglevel_bus
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComOrglevelBus() {
        return comOrglevelBus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_orglevel_bus
     *
     * @param comOrglevelBus the value for cominfo_appendix.com_orglevel_bus
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComOrglevelBus(String comOrglevelBus) {
        this.comOrglevelBus = comOrglevelBus == null ? null : comOrglevelBus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regcode_bus
     *
     * @return the value of cominfo_appendix.com_regcode_bus
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegcodeBus() {
        return comRegcodeBus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regcode_bus
     *
     * @param comRegcodeBus the value for cominfo_appendix.com_regcode_bus
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegcodeBus(String comRegcodeBus) {
        this.comRegcodeBus = comRegcodeBus == null ? null : comRegcodeBus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_orglevel_form
     *
     * @return the value of cominfo_appendix.com_orglevel_form
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComOrglevelForm() {
        return comOrglevelForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_orglevel_form
     *
     * @param comOrglevelForm the value for cominfo_appendix.com_orglevel_form
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComOrglevelForm(String comOrglevelForm) {
        this.comOrglevelForm = comOrglevelForm == null ? null : comOrglevelForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regcode_form
     *
     * @return the value of cominfo_appendix.com_regcode_form
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegcodeForm() {
        return comRegcodeForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regcode_form
     *
     * @param comRegcodeForm the value for cominfo_appendix.com_regcode_form
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegcodeForm(String comRegcodeForm) {
        this.comRegcodeForm = comRegcodeForm == null ? null : comRegcodeForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_orglevel_civil
     *
     * @return the value of cominfo_appendix.com_orglevel_civil
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComOrglevelCivil() {
        return comOrglevelCivil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_orglevel_civil
     *
     * @param comOrglevelCivil the value for cominfo_appendix.com_orglevel_civil
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComOrglevelCivil(String comOrglevelCivil) {
        this.comOrglevelCivil = comOrglevelCivil == null ? null : comOrglevelCivil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regcode_civil
     *
     * @return the value of cominfo_appendix.com_regcode_civil
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegcodeCivil() {
        return comRegcodeCivil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regcode_civil
     *
     * @param comRegcodeCivil the value for cominfo_appendix.com_regcode_civil
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegcodeCivil(String comRegcodeCivil) {
        this.comRegcodeCivil = comRegcodeCivil == null ? null : comRegcodeCivil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_orglevel_nattax
     *
     * @return the value of cominfo_appendix.com_orglevel_nattax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComOrglevelNattax() {
        return comOrglevelNattax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_orglevel_nattax
     *
     * @param comOrglevelNattax the value for cominfo_appendix.com_orglevel_nattax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComOrglevelNattax(String comOrglevelNattax) {
        this.comOrglevelNattax = comOrglevelNattax == null ? null : comOrglevelNattax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regcode_nattax
     *
     * @return the value of cominfo_appendix.com_regcode_nattax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegcodeNattax() {
        return comRegcodeNattax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regcode_nattax
     *
     * @param comRegcodeNattax the value for cominfo_appendix.com_regcode_nattax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegcodeNattax(String comRegcodeNattax) {
        this.comRegcodeNattax = comRegcodeNattax == null ? null : comRegcodeNattax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_orglevel_tax
     *
     * @return the value of cominfo_appendix.com_orglevel_tax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComOrglevelTax() {
        return comOrglevelTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_orglevel_tax
     *
     * @param comOrglevelTax the value for cominfo_appendix.com_orglevel_tax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComOrglevelTax(String comOrglevelTax) {
        this.comOrglevelTax = comOrglevelTax == null ? null : comOrglevelTax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regcode_tax
     *
     * @return the value of cominfo_appendix.com_regcode_tax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegcodeTax() {
        return comRegcodeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regcode_tax
     *
     * @param comRegcodeTax the value for cominfo_appendix.com_regcode_tax
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegcodeTax(String comRegcodeTax) {
        this.comRegcodeTax = comRegcodeTax == null ? null : comRegcodeTax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_orglevel_oth
     *
     * @return the value of cominfo_appendix.com_orglevel_oth
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComOrglevelOth() {
        return comOrglevelOth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_orglevel_oth
     *
     * @param comOrglevelOth the value for cominfo_appendix.com_orglevel_oth
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComOrglevelOth(String comOrglevelOth) {
        this.comOrglevelOth = comOrglevelOth == null ? null : comOrglevelOth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regcode_oth
     *
     * @return the value of cominfo_appendix.com_regcode_oth
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegcodeOth() {
        return comRegcodeOth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regcode_oth
     *
     * @param comRegcodeOth the value for cominfo_appendix.com_regcode_oth
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegcodeOth(String comRegcodeOth) {
        this.comRegcodeOth = comRegcodeOth == null ? null : comRegcodeOth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_stock
     *
     * @return the value of cominfo_appendix.com_stock
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComStock() {
        return comStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_stock
     *
     * @param comStock the value for cominfo_appendix.com_stock
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComStock(String comStock) {
        this.comStock = comStock == null ? null : comStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_subrel
     *
     * @return the value of cominfo_appendix.com_subrel
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComSubrel() {
        return comSubrel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_subrel
     *
     * @param comSubrel the value for cominfo_appendix.com_subrel
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComSubrel(String comSubrel) {
        this.comSubrel = comSubrel == null ? null : comSubrel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_impaccclass
     *
     * @return the value of cominfo_appendix.com_impaccclass
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComImpaccclass() {
        return comImpaccclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_impaccclass
     *
     * @param comImpaccclass the value for cominfo_appendix.com_impaccclass
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComImpaccclass(String comImpaccclass) {
        this.comImpaccclass = comImpaccclass == null ? null : comImpaccclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_isimprule
     *
     * @return the value of cominfo_appendix.com_isimprule
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComIsimprule() {
        return comIsimprule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_isimprule
     *
     * @param comIsimprule the value for cominfo_appendix.com_isimprule
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComIsimprule(String comIsimprule) {
        this.comIsimprule = comIsimprule == null ? null : comIsimprule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_comclass
     *
     * @return the value of cominfo_appendix.com_comclass
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComComclass() {
        return comComclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_comclass
     *
     * @param comComclass the value for cominfo_appendix.com_comclass
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComComclass(String comComclass) {
        this.comComclass = comComclass == null ? null : comComclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_delcomcode
     *
     * @return the value of cominfo_appendix.com_delcomcode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComDelcomcode() {
        return comDelcomcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_delcomcode
     *
     * @param comDelcomcode the value for cominfo_appendix.com_delcomcode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComDelcomcode(String comDelcomcode) {
        this.comDelcomcode = comDelcomcode == null ? null : comDelcomcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_delcomname
     *
     * @return the value of cominfo_appendix.com_delcomname
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComDelcomname() {
        return comDelcomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_delcomname
     *
     * @param comDelcomname the value for cominfo_appendix.com_delcomname
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComDelcomname(String comDelcomname) {
        this.comDelcomname = comDelcomname == null ? null : comDelcomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_delcomaddr
     *
     * @return the value of cominfo_appendix.com_delcomaddr
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComDelcomaddr() {
        return comDelcomaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_delcomaddr
     *
     * @param comDelcomaddr the value for cominfo_appendix.com_delcomaddr
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComDelcomaddr(String comDelcomaddr) {
        this.comDelcomaddr = comDelcomaddr == null ? null : comDelcomaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_delcomareacode
     *
     * @return the value of cominfo_appendix.com_delcomareacode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComDelcomareacode() {
        return comDelcomareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_delcomareacode
     *
     * @param comDelcomareacode the value for cominfo_appendix.com_delcomareacode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComDelcomareacode(String comDelcomareacode) {
        this.comDelcomareacode = comDelcomareacode == null ? null : comDelcomareacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_industrycount
     *
     * @return the value of cominfo_appendix.com_industrycount
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public Double getComIndustrycount() {
        return comIndustrycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_industrycount
     *
     * @param comIndustrycount the value for cominfo_appendix.com_industrycount
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComIndustrycount(Double comIndustrycount) {
        this.comIndustrycount = comIndustrycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_comscale
     *
     * @return the value of cominfo_appendix.com_comscale
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComComscale() {
        return comComscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_comscale
     *
     * @param comComscale the value for cominfo_appendix.com_comscale
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComComscale(String comComscale) {
        this.comComscale = comComscale == null ? null : comComscale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_citycode
     *
     * @return the value of cominfo_appendix.com_citycode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComCitycode() {
        return comCitycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_citycode
     *
     * @param comCitycode the value for cominfo_appendix.com_citycode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComCitycode(String comCitycode) {
        this.comCitycode = comCitycode == null ? null : comCitycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regcitycode
     *
     * @return the value of cominfo_appendix.com_regcitycode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegcitycode() {
        return comRegcitycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regcitycode
     *
     * @param comRegcitycode the value for cominfo_appendix.com_regcitycode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegcitycode(String comRegcitycode) {
        this.comRegcitycode = comRegcitycode == null ? null : comRegcitycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_telext
     *
     * @return the value of cominfo_appendix.com_telext
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComTelext() {
        return comTelext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_telext
     *
     * @param comTelext the value for cominfo_appendix.com_telext
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComTelext(String comTelext) {
        this.comTelext = comTelext == null ? null : comTelext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_faxext
     *
     * @return the value of cominfo_appendix.com_faxext
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComFaxext() {
        return comFaxext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_faxext
     *
     * @param comFaxext the value for cominfo_appendix.com_faxext
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComFaxext(String comFaxext) {
        this.comFaxext = comFaxext == null ? null : comFaxext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_zone
     *
     * @return the value of cominfo_appendix.com_zone
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComZone() {
        return comZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_zone
     *
     * @param comZone the value for cominfo_appendix.com_zone
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComZone(String comZone) {
        this.comZone = comZone == null ? null : comZone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_tel
     *
     * @return the value of cominfo_appendix.com_tel
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComTel() {
        return comTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_tel
     *
     * @param comTel the value for cominfo_appendix.com_tel
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComTel(String comTel) {
        this.comTel = comTel == null ? null : comTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_mobile
     *
     * @return the value of cominfo_appendix.com_mobile
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComMobile() {
        return comMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_mobile
     *
     * @param comMobile the value for cominfo_appendix.com_mobile
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComMobile(String comMobile) {
        this.comMobile = comMobile == null ? null : comMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_industrytype
     *
     * @return the value of cominfo_appendix.com_industrytype
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComIndustrytype() {
        return comIndustrytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_industrytype
     *
     * @param comIndustrytype the value for cominfo_appendix.com_industrytype
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComIndustrytype(String comIndustrytype) {
        this.comIndustrytype = comIndustrytype == null ? null : comIndustrytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_comprincipal
     *
     * @return the value of cominfo_appendix.com_comprincipal
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComComprincipal() {
        return comComprincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_comprincipal
     *
     * @param comComprincipal the value for cominfo_appendix.com_comprincipal
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComComprincipal(String comComprincipal) {
        this.comComprincipal = comComprincipal == null ? null : comComprincipal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_staprincipal
     *
     * @return the value of cominfo_appendix.com_staprincipal
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComStaprincipal() {
        return comStaprincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_staprincipal
     *
     * @param comStaprincipal the value for cominfo_appendix.com_staprincipal
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComStaprincipal(String comStaprincipal) {
        this.comStaprincipal = comStaprincipal == null ? null : comStaprincipal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_fillperson
     *
     * @return the value of cominfo_appendix.com_fillperson
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComFillperson() {
        return comFillperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_fillperson
     *
     * @param comFillperson the value for cominfo_appendix.com_fillperson
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComFillperson(String comFillperson) {
        this.comFillperson = comFillperson == null ? null : comFillperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_contacttel
     *
     * @return the value of cominfo_appendix.com_contacttel
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComContacttel() {
        return comContacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_contacttel
     *
     * @param comContacttel the value for cominfo_appendix.com_contacttel
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComContacttel(String comContacttel) {
        this.comContacttel = comContacttel == null ? null : comContacttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_adddate
     *
     * @return the value of cominfo_appendix.com_adddate
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public Date getComAdddate() {
        return comAdddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_adddate
     *
     * @param comAdddate the value for cominfo_appendix.com_adddate
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComAdddate(Date comAdddate) {
        this.comAdddate = comAdddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_groupid
     *
     * @return the value of cominfo_appendix.com_groupid
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public Double getComGroupid() {
        return comGroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_groupid
     *
     * @param comGroupid the value for cominfo_appendix.com_groupid
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComGroupid(Double comGroupid) {
        this.comGroupid = comGroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_imgurl
     *
     * @return the value of cominfo_appendix.com_imgurl
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComImgurl() {
        return comImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_imgurl
     *
     * @param comImgurl the value for cominfo_appendix.com_imgurl
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComImgurl(String comImgurl) {
        this.comImgurl = comImgurl == null ? null : comImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_status
     *
     * @return the value of cominfo_appendix.com_status
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public Double getComStatus() {
        return comStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_status
     *
     * @param comStatus the value for cominfo_appendix.com_status
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComStatus(Double comStatus) {
        this.comStatus = comStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_apply
     *
     * @return the value of cominfo_appendix.com_apply
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComApply() {
        return comApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_apply
     *
     * @param comApply the value for cominfo_appendix.com_apply
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComApply(String comApply) {
        this.comApply = comApply == null ? null : comApply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_reply
     *
     * @return the value of cominfo_appendix.com_reply
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComReply() {
        return comReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_reply
     *
     * @param comReply the value for cominfo_appendix.com_reply
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComReply(String comReply) {
        this.comReply = comReply == null ? null : comReply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_industry
     *
     * @return the value of cominfo_appendix.com_industry
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComIndustry() {
        return comIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_industry
     *
     * @param comIndustry the value for cominfo_appendix.com_industry
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComIndustry(String comIndustry) {
        this.comIndustry = comIndustry == null ? null : comIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_address_sheng
     *
     * @return the value of cominfo_appendix.com_address_sheng
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComAddressSheng() {
        return comAddressSheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_address_sheng
     *
     * @param comAddressSheng the value for cominfo_appendix.com_address_sheng
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComAddressSheng(String comAddressSheng) {
        this.comAddressSheng = comAddressSheng == null ? null : comAddressSheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_address_di
     *
     * @return the value of cominfo_appendix.com_address_di
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComAddressDi() {
        return comAddressDi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_address_di
     *
     * @param comAddressDi the value for cominfo_appendix.com_address_di
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComAddressDi(String comAddressDi) {
        this.comAddressDi = comAddressDi == null ? null : comAddressDi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_address_xian
     *
     * @return the value of cominfo_appendix.com_address_xian
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComAddressXian() {
        return comAddressXian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_address_xian
     *
     * @param comAddressXian the value for cominfo_appendix.com_address_xian
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComAddressXian(String comAddressXian) {
        this.comAddressXian = comAddressXian == null ? null : comAddressXian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_address_jie
     *
     * @return the value of cominfo_appendix.com_address_jie
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComAddressJie() {
        return comAddressJie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_address_jie
     *
     * @param comAddressJie the value for cominfo_appendix.com_address_jie
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComAddressJie(String comAddressJie) {
        this.comAddressJie = comAddressJie == null ? null : comAddressJie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_address_she
     *
     * @return the value of cominfo_appendix.com_address_she
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComAddressShe() {
        return comAddressShe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_address_she
     *
     * @param comAddressShe the value for cominfo_appendix.com_address_she
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComAddressShe(String comAddressShe) {
        this.comAddressShe = comAddressShe == null ? null : comAddressShe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_address
     *
     * @return the value of cominfo_appendix.com_address
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComAddress() {
        return comAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_address
     *
     * @param comAddress the value for cominfo_appendix.com_address
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComAddress(String comAddress) {
        this.comAddress = comAddress == null ? null : comAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_regaddr
     *
     * @return the value of cominfo_appendix.com_regaddr
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComRegaddr() {
        return comRegaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_regaddr
     *
     * @param comRegaddr the value for cominfo_appendix.com_regaddr
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComRegaddr(String comRegaddr) {
        this.comRegaddr = comRegaddr == null ? null : comRegaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.com_loc_areacode
     *
     * @return the value of cominfo_appendix.com_loc_areacode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public String getComLocAreacode() {
        return comLocAreacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.com_loc_areacode
     *
     * @param comLocAreacode the value for cominfo_appendix.com_loc_areacode
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setComLocAreacode(String comLocAreacode) {
        this.comLocAreacode = comLocAreacode == null ? null : comLocAreacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.gmt_create
     *
     * @return the value of cominfo_appendix.gmt_create
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.gmt_create
     *
     * @param gmtCreate the value for cominfo_appendix.gmt_create
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo_appendix.gmt_modified
     *
     * @return the value of cominfo_appendix.gmt_modified
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo_appendix.gmt_modified
     *
     * @param gmtModified the value for cominfo_appendix.gmt_modified
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}