package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class ComInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.id
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.com_code
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private String comCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.com_name
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private String comName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.com_comtype
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private String comComtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.com_orgtype
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private String comOrgtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.com_industrycode
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private String comIndustrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.com_regtype
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private String comRegtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.com_businessstatus
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private String comBusinessstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.com_address_county
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private String comAddressCounty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.industry_id
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private Industry industry;

    private Integer industryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.gmt_create
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cominfo.gmt_modified
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.id
     *
     * @return the value of cominfo.id
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.id
     *
     * @param id the value for cominfo.id
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.com_code
     *
     * @return the value of cominfo.com_code
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public String getComCode() {
        return comCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.com_code
     *
     * @param comCode the value for cominfo.com_code
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setComCode(String comCode) {
        this.comCode = comCode == null ? null : comCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.com_name
     *
     * @return the value of cominfo.com_name
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.com_name
     *
     * @param comName the value for cominfo.com_name
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.com_comtype
     *
     * @return the value of cominfo.com_comtype
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public String getComComtype() {
        return comComtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.com_comtype
     *
     * @param comComtype the value for cominfo.com_comtype
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setComComtype(String comComtype) {
        this.comComtype = comComtype == null ? null : comComtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.com_orgtype
     *
     * @return the value of cominfo.com_orgtype
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public String getComOrgtype() {
        return comOrgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.com_orgtype
     *
     * @param comOrgtype the value for cominfo.com_orgtype
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setComOrgtype(String comOrgtype) {
        this.comOrgtype = comOrgtype == null ? null : comOrgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.com_industrycode
     *
     * @return the value of cominfo.com_industrycode
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public String getComIndustrycode() {
        return comIndustrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.com_industrycode
     *
     * @param comIndustrycode the value for cominfo.com_industrycode
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setComIndustrycode(String comIndustrycode) {
        this.comIndustrycode = comIndustrycode == null ? null : comIndustrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.com_regtype
     *
     * @return the value of cominfo.com_regtype
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public String getComRegtype() {
        return comRegtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.com_regtype
     *
     * @param comRegtype the value for cominfo.com_regtype
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setComRegtype(String comRegtype) {
        this.comRegtype = comRegtype == null ? null : comRegtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.com_businessstatus
     *
     * @return the value of cominfo.com_businessstatus
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public String getComBusinessstatus() {
        return comBusinessstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.com_businessstatus
     *
     * @param comBusinessstatus the value for cominfo.com_businessstatus
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setComBusinessstatus(String comBusinessstatus) {
        this.comBusinessstatus = comBusinessstatus == null ? null : comBusinessstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.com_address_county
     *
     * @return the value of cominfo.com_address_county
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public String getComAddressCounty() {
        return comAddressCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.com_address_county
     *
     * @param comAddressCounty the value for cominfo.com_address_county
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setComAddressCounty(String comAddressCounty) {
        this.comAddressCounty = comAddressCounty == null ? null : comAddressCounty.trim();
    }

    public Industry getIndustry() {
        return industry;
    }

    public void setIndustry(Industry industry) {
        this.industry = industry;
    }

    public Integer getIndustryId() {
        return industryId;
    }

    public void setIndustryId(Integer industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.gmt_create
     *
     * @return the value of cominfo.gmt_create
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.gmt_create
     *
     * @param gmtCreate the value for cominfo.gmt_create
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cominfo.gmt_modified
     *
     * @return the value of cominfo.gmt_modified
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cominfo.gmt_modified
     *
     * @param gmtModified the value for cominfo.gmt_modified
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}