package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class FormFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.form_type
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String formType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.start_point
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String startPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.end_point
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String endPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.start_time
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.end_time
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.start_user_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String startUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.start_user_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long startUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.start_unit_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long startUnitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.end_user_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String endUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.end_user_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long endUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.end_unit_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Integer endUnitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.remark
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.signed
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Byte signed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.weight
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.is_submited
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Byte isSubmited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.submit_status
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String submitStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.pro_suggest
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String proSuggest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.report_data_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long reportDataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_flow.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.id
     *
     * @return the value of form_flow.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.id
     *
     * @param id the value for form_flow.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.form_type
     *
     * @return the value of form_flow.form_type
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getFormType() {
        return formType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.form_type
     *
     * @param formType the value for form_flow.form_type
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setFormType(String formType) {
        this.formType = formType == null ? null : formType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.start_point
     *
     * @return the value of form_flow.start_point
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getStartPoint() {
        return startPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.start_point
     *
     * @param startPoint the value for form_flow.start_point
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setStartPoint(String startPoint) {
        this.startPoint = startPoint == null ? null : startPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.end_point
     *
     * @return the value of form_flow.end_point
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getEndPoint() {
        return endPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.end_point
     *
     * @param endPoint the value for form_flow.end_point
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint == null ? null : endPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.start_time
     *
     * @return the value of form_flow.start_time
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.start_time
     *
     * @param startTime the value for form_flow.start_time
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.end_time
     *
     * @return the value of form_flow.end_time
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.end_time
     *
     * @param endTime the value for form_flow.end_time
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.start_user_name
     *
     * @return the value of form_flow.start_user_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getStartUserName() {
        return startUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.start_user_name
     *
     * @param startUserName the value for form_flow.start_user_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setStartUserName(String startUserName) {
        this.startUserName = startUserName == null ? null : startUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.start_user_id
     *
     * @return the value of form_flow.start_user_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getStartUserId() {
        return startUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.start_user_id
     *
     * @param startUserId the value for form_flow.start_user_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setStartUserId(Long startUserId) {
        this.startUserId = startUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.start_unit_id
     *
     * @return the value of form_flow.start_unit_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getStartUnitId() {
        return startUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.start_unit_id
     *
     * @param startUnitId the value for form_flow.start_unit_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setStartUnitId(Long startUnitId) {
        this.startUnitId = startUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.end_user_name
     *
     * @return the value of form_flow.end_user_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getEndUserName() {
        return endUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.end_user_name
     *
     * @param endUserName the value for form_flow.end_user_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setEndUserName(String endUserName) {
        this.endUserName = endUserName == null ? null : endUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.end_user_id
     *
     * @return the value of form_flow.end_user_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getEndUserId() {
        return endUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.end_user_id
     *
     * @param endUserId the value for form_flow.end_user_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setEndUserId(Long endUserId) {
        this.endUserId = endUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.end_unit_id
     *
     * @return the value of form_flow.end_unit_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Integer getEndUnitId() {
        return endUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.end_unit_id
     *
     * @param endUnitId the value for form_flow.end_unit_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setEndUnitId(Integer endUnitId) {
        this.endUnitId = endUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.remark
     *
     * @return the value of form_flow.remark
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.remark
     *
     * @param remark the value for form_flow.remark
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.signed
     *
     * @return the value of form_flow.signed
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Byte getSigned() {
        return signed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.signed
     *
     * @param signed the value for form_flow.signed
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setSigned(Byte signed) {
        this.signed = signed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.weight
     *
     * @return the value of form_flow.weight
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.weight
     *
     * @param weight the value for form_flow.weight
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.is_submited
     *
     * @return the value of form_flow.is_submited
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Byte getIsSubmited() {
        return isSubmited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.is_submited
     *
     * @param isSubmited the value for form_flow.is_submited
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setIsSubmited(Byte isSubmited) {
        this.isSubmited = isSubmited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.submit_status
     *
     * @return the value of form_flow.submit_status
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getSubmitStatus() {
        return submitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.submit_status
     *
     * @param submitStatus the value for form_flow.submit_status
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setSubmitStatus(String submitStatus) {
        this.submitStatus = submitStatus == null ? null : submitStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.pro_suggest
     *
     * @return the value of form_flow.pro_suggest
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getProSuggest() {
        return proSuggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.pro_suggest
     *
     * @param proSuggest the value for form_flow.pro_suggest
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setProSuggest(String proSuggest) {
        this.proSuggest = proSuggest == null ? null : proSuggest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.report_data_id
     *
     * @return the value of form_flow.report_data_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getReportDataId() {
        return reportDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.report_data_id
     *
     * @param reportDataId the value for form_flow.report_data_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setReportDataId(Long reportDataId) {
        this.reportDataId = reportDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.gmt_create
     *
     * @return the value of form_flow.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.gmt_create
     *
     * @param gmtCreate the value for form_flow.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_flow.gmt_modified
     *
     * @return the value of form_flow.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_flow.gmt_modified
     *
     * @param gmtModified the value for form_flow.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}