package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class Industry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.id
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.code
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.name
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.type
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.gmt_create
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry.gmt_modified
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.id
     *
     * @return the value of industry.id
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.id
     *
     * @param id the value for industry.id
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.code
     *
     * @return the value of industry.code
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.code
     *
     * @param code the value for industry.code
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.name
     *
     * @return the value of industry.name
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.name
     *
     * @param name the value for industry.name
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.type
     *
     * @return the value of industry.type
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.type
     *
     * @param type the value for industry.type
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.gmt_create
     *
     * @return the value of industry.gmt_create
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.gmt_create
     *
     * @param gmtCreate the value for industry.gmt_create
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry.gmt_modified
     *
     * @return the value of industry.gmt_modified
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry.gmt_modified
     *
     * @param gmtModified the value for industry.gmt_modified
     *
     * @mbg.generated Tue Dec 29 10:48:10 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}