package com.hyjj.hyjjservice.dataobject;

import org.apache.ibatis.annotations.Param;

import java.util.Date;

public class PublishKeyword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_keyword.id
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */

    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_keyword.keyword
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_keyword.publish_id
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    private Long publishId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_keyword.gmt_create
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_keyword.gmt_modified
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_keyword.id
     *
     * @return the value of publish_keyword.id
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_keyword.id
     *
     * @param id the value for publish_keyword.id
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_keyword.keyword
     *
     * @return the value of publish_keyword.keyword
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_keyword.keyword
     *
     * @param keyword the value for publish_keyword.keyword
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_keyword.publish_id
     *
     * @return the value of publish_keyword.publish_id
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public Long getPublishId() {
        return publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_keyword.publish_id
     *
     * @param publishId the value for publish_keyword.publish_id
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public void setPublishId(Long publishId) {
        this.publishId = publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_keyword.gmt_create
     *
     * @return the value of publish_keyword.gmt_create
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_keyword.gmt_create
     *
     * @param gmtCreate the value for publish_keyword.gmt_create
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_keyword.gmt_modified
     *
     * @return the value of publish_keyword.gmt_modified
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_keyword.gmt_modified
     *
     * @param gmtModified the value for publish_keyword.gmt_modified
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }


    @Override
    public String toString() {
        return "PublishKeyword{" +
                "id=" + id +
                ", keyword='" + keyword + '\'' +
                ", publishId=" + publishId +
                ", gmtCreate=" + gmtCreate +
                ", gmtModified=" + gmtModified +
                '}';
    }
}