package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class ReportData {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.fill_person
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String fillPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.fill_unit
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String fillUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.add_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date addDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.area_name
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.report_template_id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Long reportTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.area_code
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.begin_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.end_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.submit_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date submitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.pro_status
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String proStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.pro_status_name
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String proStatusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.process_id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Long processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.statistics_principal
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String statisticsPrincipal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.unit_principal
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String unitPrincipal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.head_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String headHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.body_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String bodyHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.tail_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String tailHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.org_code
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.expire_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.audit_id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String auditId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.enterprise_name
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.data_from
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String dataFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.enterprise
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String enterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.gmt_create
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.gmt_modified
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.report_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date reportDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data.fill_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date fillDate;

    private int isSave;

    public int getIsSave() {
        return isSave;
    }

    public void setIsSave(int isSave) {
        this.isSave = isSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.id
     *
     * @return the value of report_data.id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.id
     *
     * @param id the value for report_data.id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.fill_person
     *
     * @return the value of report_data.fill_person
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getFillPerson() {
        return fillPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.fill_person
     *
     * @param fillPerson the value for report_data.fill_person
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setFillPerson(String fillPerson) {
        this.fillPerson = fillPerson == null ? null : fillPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.fill_unit
     *
     * @return the value of report_data.fill_unit
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getFillUnit() {
        return fillUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.fill_unit
     *
     * @param fillUnit the value for report_data.fill_unit
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setFillUnit(String fillUnit) {
        this.fillUnit = fillUnit == null ? null : fillUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.add_date
     *
     * @return the value of report_data.add_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.add_date
     *
     * @param addDate the value for report_data.add_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.area_name
     *
     * @return the value of report_data.area_name
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.area_name
     *
     * @param areaName the value for report_data.area_name
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.report_template_id
     *
     * @return the value of report_data.report_template_id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Long getReportTemplateId() {
        return reportTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.report_template_id
     *
     * @param reportTemplateId the value for report_data.report_template_id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setReportTemplateId(Long reportTemplateId) {
        this.reportTemplateId = reportTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.area_code
     *
     * @return the value of report_data.area_code
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.area_code
     *
     * @param areaCode the value for report_data.area_code
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.begin_date
     *
     * @return the value of report_data.begin_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.begin_date
     *
     * @param beginDate the value for report_data.begin_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.end_date
     *
     * @return the value of report_data.end_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.end_date
     *
     * @param endDate the value for report_data.end_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.submit_date
     *
     * @return the value of report_data.submit_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.submit_date
     *
     * @param submitDate the value for report_data.submit_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.pro_status
     *
     * @return the value of report_data.pro_status
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getProStatus() {
        return proStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.pro_status
     *
     * @param proStatus the value for report_data.pro_status
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setProStatus(String proStatus) {
        this.proStatus = proStatus == null ? null : proStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.pro_status_name
     *
     * @return the value of report_data.pro_status_name
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getProStatusName() {
        return proStatusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.pro_status_name
     *
     * @param proStatusName the value for report_data.pro_status_name
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setProStatusName(String proStatusName) {
        this.proStatusName = proStatusName == null ? null : proStatusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.process_id
     *
     * @return the value of report_data.process_id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Long getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.process_id
     *
     * @param processId the value for report_data.process_id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setProcessId(Long processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.statistics_principal
     *
     * @return the value of report_data.statistics_principal
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getStatisticsPrincipal() {
        return statisticsPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.statistics_principal
     *
     * @param statisticsPrincipal the value for report_data.statistics_principal
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setStatisticsPrincipal(String statisticsPrincipal) {
        this.statisticsPrincipal = statisticsPrincipal == null ? null : statisticsPrincipal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.unit_principal
     *
     * @return the value of report_data.unit_principal
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getUnitPrincipal() {
        return unitPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.unit_principal
     *
     * @param unitPrincipal the value for report_data.unit_principal
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setUnitPrincipal(String unitPrincipal) {
        this.unitPrincipal = unitPrincipal == null ? null : unitPrincipal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.head_html
     *
     * @return the value of report_data.head_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getHeadHtml() {
        return headHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.head_html
     *
     * @param headHtml the value for report_data.head_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setHeadHtml(String headHtml) {
        this.headHtml = headHtml == null ? null : headHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.body_html
     *
     * @return the value of report_data.body_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getBodyHtml() {
        return bodyHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.body_html
     *
     * @param bodyHtml the value for report_data.body_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setBodyHtml(String bodyHtml) {
        this.bodyHtml = bodyHtml == null ? null : bodyHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.tail_html
     *
     * @return the value of report_data.tail_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getTailHtml() {
        return tailHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.tail_html
     *
     * @param tailHtml the value for report_data.tail_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setTailHtml(String tailHtml) {
        this.tailHtml = tailHtml == null ? null : tailHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.org_code
     *
     * @return the value of report_data.org_code
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.org_code
     *
     * @param orgCode the value for report_data.org_code
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.expire_date
     *
     * @return the value of report_data.expire_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.expire_date
     *
     * @param expireDate the value for report_data.expire_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.audit_id
     *
     * @return the value of report_data.audit_id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.audit_id
     *
     * @param auditId the value for report_data.audit_id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setAuditId(String auditId) {
        this.auditId = auditId == null ? null : auditId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.enterprise_name
     *
     * @return the value of report_data.enterprise_name
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.enterprise_name
     *
     * @param enterpriseName the value for report_data.enterprise_name
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.data_from
     *
     * @return the value of report_data.data_from
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.data_from
     *
     * @param dataFrom the value for report_data.data_from
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setDataFrom(String dataFrom) {
        this.dataFrom = dataFrom == null ? null : dataFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.enterprise
     *
     * @return the value of report_data.enterprise
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.enterprise
     *
     * @param enterprise the value for report_data.enterprise
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setEnterprise(String enterprise) {
        this.enterprise = enterprise == null ? null : enterprise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.gmt_create
     *
     * @return the value of report_data.gmt_create
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.gmt_create
     *
     * @param gmtCreate the value for report_data.gmt_create
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.gmt_modified
     *
     * @return the value of report_data.gmt_modified
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.gmt_modified
     *
     * @param gmtModified the value for report_data.gmt_modified
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.report_date
     *
     * @return the value of report_data.report_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getReportDate() {
        return reportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.report_date
     *
     * @param reportDate the value for report_data.report_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data.fill_date
     *
     * @return the value of report_data.fill_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getFillDate() {
        return fillDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data.fill_date
     *
     * @param fillDate the value for report_data.fill_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setFillDate(Date fillDate) {
        this.fillDate = fillDate;
    }
}