package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class ReportDataRow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data_row.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data_row.row_order
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Integer rowOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data_row.report_data_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long reportDataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data_row.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_data_row.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data_row.id
     *
     * @return the value of report_data_row.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data_row.id
     *
     * @param id the value for report_data_row.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data_row.row_order
     *
     * @return the value of report_data_row.row_order
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Integer getRowOrder() {
        return rowOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data_row.row_order
     *
     * @param rowOrder the value for report_data_row.row_order
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setRowOrder(Integer rowOrder) {
        this.rowOrder = rowOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data_row.report_data_id
     *
     * @return the value of report_data_row.report_data_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getReportDataId() {
        return reportDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data_row.report_data_id
     *
     * @param reportDataId the value for report_data_row.report_data_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setReportDataId(Long reportDataId) {
        this.reportDataId = reportDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data_row.gmt_create
     *
     * @return the value of report_data_row.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data_row.gmt_create
     *
     * @param gmtCreate the value for report_data_row.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_data_row.gmt_modified
     *
     * @return the value of report_data_row.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_data_row.gmt_modified
     *
     * @param gmtModified the value for report_data_row.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}