package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class ReportTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.type
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.title
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.number
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.made_rep_org
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String madeRepOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.auditing_org
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String auditingOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.auditing_code
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String auditingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.expire_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.remark
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.insert_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.rep_class
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Byte repClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.head_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String headHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.body_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String bodyHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.tail_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String tailHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.template_path
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String templatePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.row_index
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Integer rowIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.var_row_flag
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private String varRowFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.show_order
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Integer showOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.gmt_create
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_template.gmt_modified
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.id
     *
     * @return the value of report_template.id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.id
     *
     * @param id the value for report_template.id
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.type
     *
     * @return the value of report_template.type
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.type
     *
     * @param type the value for report_template.type
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.title
     *
     * @return the value of report_template.title
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.title
     *
     * @param title the value for report_template.title
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.number
     *
     * @return the value of report_template.number
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.number
     *
     * @param number the value for report_template.number
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.made_rep_org
     *
     * @return the value of report_template.made_rep_org
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getMadeRepOrg() {
        return madeRepOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.made_rep_org
     *
     * @param madeRepOrg the value for report_template.made_rep_org
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setMadeRepOrg(String madeRepOrg) {
        this.madeRepOrg = madeRepOrg == null ? null : madeRepOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.auditing_org
     *
     * @return the value of report_template.auditing_org
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getAuditingOrg() {
        return auditingOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.auditing_org
     *
     * @param auditingOrg the value for report_template.auditing_org
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setAuditingOrg(String auditingOrg) {
        this.auditingOrg = auditingOrg == null ? null : auditingOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.auditing_code
     *
     * @return the value of report_template.auditing_code
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getAuditingCode() {
        return auditingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.auditing_code
     *
     * @param auditingCode the value for report_template.auditing_code
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setAuditingCode(String auditingCode) {
        this.auditingCode = auditingCode == null ? null : auditingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.expire_date
     *
     * @return the value of report_template.expire_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.expire_date
     *
     * @param expireDate the value for report_template.expire_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.remark
     *
     * @return the value of report_template.remark
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.remark
     *
     * @param remark the value for report_template.remark
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.insert_date
     *
     * @return the value of report_template.insert_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.insert_date
     *
     * @param insertDate the value for report_template.insert_date
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.rep_class
     *
     * @return the value of report_template.rep_class
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Byte getRepClass() {
        return repClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.rep_class
     *
     * @param repClass the value for report_template.rep_class
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setRepClass(Byte repClass) {
        this.repClass = repClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.head_html
     *
     * @return the value of report_template.head_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getHeadHtml() {
        return headHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.head_html
     *
     * @param headHtml the value for report_template.head_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setHeadHtml(String headHtml) {
        this.headHtml = headHtml == null ? null : headHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.body_html
     *
     * @return the value of report_template.body_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getBodyHtml() {
        return bodyHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.body_html
     *
     * @param bodyHtml the value for report_template.body_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setBodyHtml(String bodyHtml) {
        this.bodyHtml = bodyHtml == null ? null : bodyHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.tail_html
     *
     * @return the value of report_template.tail_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getTailHtml() {
        return tailHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.tail_html
     *
     * @param tailHtml the value for report_template.tail_html
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setTailHtml(String tailHtml) {
        this.tailHtml = tailHtml == null ? null : tailHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.template_path
     *
     * @return the value of report_template.template_path
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getTemplatePath() {
        return templatePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.template_path
     *
     * @param templatePath the value for report_template.template_path
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setTemplatePath(String templatePath) {
        this.templatePath = templatePath == null ? null : templatePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.row_index
     *
     * @return the value of report_template.row_index
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Integer getRowIndex() {
        return rowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.row_index
     *
     * @param rowIndex the value for report_template.row_index
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setRowIndex(Integer rowIndex) {
        this.rowIndex = rowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.var_row_flag
     *
     * @return the value of report_template.var_row_flag
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public String getVarRowFlag() {
        return varRowFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.var_row_flag
     *
     * @param varRowFlag the value for report_template.var_row_flag
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setVarRowFlag(String varRowFlag) {
        this.varRowFlag = varRowFlag == null ? null : varRowFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.show_order
     *
     * @return the value of report_template.show_order
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.show_order
     *
     * @param showOrder the value for report_template.show_order
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.gmt_create
     *
     * @return the value of report_template.gmt_create
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.gmt_create
     *
     * @param gmtCreate the value for report_template.gmt_create
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_template.gmt_modified
     *
     * @return the value of report_template.gmt_modified
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_template.gmt_modified
     *
     * @param gmtModified the value for report_template.gmt_modified
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    private String row;
    private String col;

    public String getRow() {
        return row;
    }

    public void setRow(String row) {
        this.row = row;
    }

    public String getCol() {
        return col;
    }

    public void setCol(String col) {
        this.col = col;
    }

    private String dataRow;
    private String dataCol;

    public String getDataRow() {
        return dataRow;
    }

    public void setDataRow(String dataRow) {
        this.dataRow = dataRow;
    }

    public String getDataCol() {
        return dataCol;
    }

    public void setDataCol(String dataCol) {
        this.dataCol = dataCol;
    }

    private String allValueRow;
    private String allValueCol;

    public String getAllValueRow() {
        return allValueRow;
    }

    public void setAllValueRow(String allValueRow) {
        this.allValueRow = allValueRow;
    }

    public String getAllValueCol() {
        return allValueCol;
    }

    public void setAllValueCol(String allValueCol) {
        this.allValueCol = allValueCol;
    }
}