package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.is_use
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private Byte isUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.gmt_create
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.gmt_modified
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.is_use
     *
     * @return the value of role.is_use
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public Byte getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.is_use
     *
     * @param isUse the value for role.is_use
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setIsUse(Byte isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.gmt_create
     *
     * @return the value of role.gmt_create
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.gmt_create
     *
     * @param gmtCreate the value for role.gmt_create
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.gmt_modified
     *
     * @return the value of role.gmt_modified
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.gmt_modified
     *
     * @param gmtModified the value for role.gmt_modified
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}