package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class RoleAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.role_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.authority_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Integer authorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.is_used
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Boolean isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.gmt_create
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority.gmt_modified
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.id
     *
     * @return the value of role_authority.id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.id
     *
     * @param id the value for role_authority.id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.role_id
     *
     * @return the value of role_authority.role_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.role_id
     *
     * @param roleId the value for role_authority.role_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.authority_id
     *
     * @return the value of role_authority.authority_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.authority_id
     *
     * @param authorityId the value for role_authority.authority_id
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.is_used
     *
     * @return the value of role_authority.is_used
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Boolean getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.is_used
     *
     * @param isUsed the value for role_authority.is_used
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setIsUsed(Boolean isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.gmt_create
     *
     * @return the value of role_authority.gmt_create
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.gmt_create
     *
     * @param gmtCreate the value for role_authority.gmt_create
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority.gmt_modified
     *
     * @return the value of role_authority.gmt_modified
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority.gmt_modified
     *
     * @param gmtModified the value for role_authority.gmt_modified
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}