package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class RowTargetName {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column row_target_name.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column row_target_name.target_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String targetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column row_target_name.report_data_row_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long reportDataRowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column row_target_name.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column row_target_name.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column row_target_name.id
     *
     * @return the value of row_target_name.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column row_target_name.id
     *
     * @param id the value for row_target_name.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column row_target_name.target_name
     *
     * @return the value of row_target_name.target_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column row_target_name.target_name
     *
     * @param targetName the value for row_target_name.target_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName == null ? null : targetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column row_target_name.report_data_row_id
     *
     * @return the value of row_target_name.report_data_row_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getReportDataRowId() {
        return reportDataRowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column row_target_name.report_data_row_id
     *
     * @param reportDataRowId the value for row_target_name.report_data_row_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setReportDataRowId(Long reportDataRowId) {
        this.reportDataRowId = reportDataRowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column row_target_name.gmt_create
     *
     * @return the value of row_target_name.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column row_target_name.gmt_create
     *
     * @param gmtCreate the value for row_target_name.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column row_target_name.gmt_modified
     *
     * @return the value of row_target_name.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column row_target_name.gmt_modified
     *
     * @param gmtModified the value for row_target_name.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}