package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class StatisticsTargetKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_target_key.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_target_key.target_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String targetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_target_key.unit
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_target_key.add_time
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_target_key.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_target_key.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_target_key.parent_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_target_key.id
     *
     * @return the value of statistics_target_key.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_target_key.id
     *
     * @param id the value for statistics_target_key.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_target_key.target_name
     *
     * @return the value of statistics_target_key.target_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_target_key.target_name
     *
     * @param targetName the value for statistics_target_key.target_name
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName == null ? null : targetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_target_key.unit
     *
     * @return the value of statistics_target_key.unit
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_target_key.unit
     *
     * @param unit the value for statistics_target_key.unit
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_target_key.add_time
     *
     * @return the value of statistics_target_key.add_time
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_target_key.add_time
     *
     * @param addTime the value for statistics_target_key.add_time
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_target_key.gmt_create
     *
     * @return the value of statistics_target_key.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_target_key.gmt_create
     *
     * @param gmtCreate the value for statistics_target_key.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_target_key.gmt_modified
     *
     * @return the value of statistics_target_key.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_target_key.gmt_modified
     *
     * @param gmtModified the value for statistics_target_key.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_target_key.parent_id
     *
     * @return the value of statistics_target_key.parent_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_target_key.parent_id
     *
     * @param parentId the value for statistics_target_key.parent_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}