package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class TargetValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_value.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_value.target_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Double targetValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_value.row_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long rowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_value.col_order
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Integer colOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_value.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_value.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_value.id
     *
     * @return the value of target_value.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_value.id
     *
     * @param id the value for target_value.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_value.target_value
     *
     * @return the value of target_value.target_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Double getTargetValue() {
        return targetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_value.target_value
     *
     * @param targetValue the value for target_value.target_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setTargetValue(Double targetValue) {
        this.targetValue = targetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_value.row_id
     *
     * @return the value of target_value.row_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_value.row_id
     *
     * @param rowId the value for target_value.row_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setRowId(Long rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_value.col_order
     *
     * @return the value of target_value.col_order
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Integer getColOrder() {
        return colOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_value.col_order
     *
     * @param colOrder the value for target_value.col_order
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setColOrder(Integer colOrder) {
        this.colOrder = colOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_value.gmt_create
     *
     * @return the value of target_value.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_value.gmt_create
     *
     * @param gmtCreate the value for target_value.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_value.gmt_modified
     *
     * @return the value of target_value.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_value.gmt_modified
     *
     * @param gmtModified the value for target_value.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}