package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class TargetKeyValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_key_value.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_key_value.value_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long valueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_key_value.target_key_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Long targetKeyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_key_value.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_key_value.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    private Date gmtModified;


    private Long reportDataId;

    public Long getReportDataId() {
        return reportDataId;
    }

    public void setReportDataId(Long reportDataId) {
        this.reportDataId = reportDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_key_value.id
     *
     * @return the value of target_key_value.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_key_value.id
     *
     * @param id the value for target_key_value.id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_key_value.value_id
     *
     * @return the value of target_key_value.value_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getValueId() {
        return valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_key_value.value_id
     *
     * @param valueId the value for target_key_value.value_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setValueId(Long valueId) {
        this.valueId = valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_key_value.target_key_id
     *
     * @return the value of target_key_value.target_key_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Long getTargetKeyId() {
        return targetKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_key_value.target_key_id
     *
     * @param targetKeyId the value for target_key_value.target_key_id
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setTargetKeyId(Long targetKeyId) {
        this.targetKeyId = targetKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_key_value.gmt_create
     *
     * @return the value of target_key_value.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_key_value.gmt_create
     *
     * @param gmtCreate the value for target_key_value.gmt_create
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_key_value.gmt_modified
     *
     * @return the value of target_key_value.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_key_value.gmt_modified
     *
     * @param gmtModified the value for target_key_value.gmt_modified
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}