package com.hyjj.hyjjservice.dataobject;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String comName;

    public String getComName() {
        return comName;
    }

    public void setComName(String comName) {
        this.comName = comName;
    }

    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.statue
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String statue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.remark
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone_number
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.creat_datatime
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private Date creatDatatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_ip
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String lastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_datatime
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private Date lastDatatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.area
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cominfo_id
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private Long cominfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_create
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_modified
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.statue
     *
     * @return the value of user.statue
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getStatue() {
        return statue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.statue
     *
     * @param statue the value for user.statue
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setStatue(String statue) {
        this.statue = statue == null ? null : statue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.remark
     *
     * @return the value of user.remark
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.remark
     *
     * @param remark the value for user.remark
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone_number
     *
     * @return the value of user.phone_number
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone_number
     *
     * @param phoneNumber the value for user.phone_number
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.creat_datatime
     *
     * @return the value of user.creat_datatime
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public Date getCreatDatatime() {
        return creatDatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.creat_datatime
     *
     * @param creatDatatime the value for user.creat_datatime
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setCreatDatatime(Date creatDatatime) {
        this.creatDatatime = creatDatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_ip
     *
     * @return the value of user.last_ip
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_ip
     *
     * @param lastIp the value for user.last_ip
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_datatime
     *
     * @return the value of user.last_datatime
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public Date getLastDatatime() {
        return lastDatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_datatime
     *
     * @param lastDatatime the value for user.last_datatime
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setLastDatatime(Date lastDatatime) {
        this.lastDatatime = lastDatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.area
     *
     * @return the value of user.area
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.area
     *
     * @param area the value for user.area
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cominfo_id
     *
     * @return the value of user.cominfo_id
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public Long getCominfoId() {
        return cominfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cominfo_id
     *
     * @param cominfoId the value for user.cominfo_id
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setCominfoId(Long cominfoId) {
        this.cominfoId = cominfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_create
     *
     * @return the value of user.gmt_create
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_create
     *
     * @param gmtCreate the value for user.gmt_create
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_modified
     *
     * @return the value of user.gmt_modified
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_modified
     *
     * @param gmtModified the value for user.gmt_modified
     *
     * @mbg.generated Sat Mar 06 22:10:39 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }


    @Override
    public String toString() {
        return "User{" +
                "comName='" + comName + '\'' +
                ", id=" + id +
                ", account='" + account + '\'' +
                ", password='" + password + '\'' +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", statue='" + statue + '\'' +
                ", remark='" + remark + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", creatDatatime=" + creatDatatime +
                ", lastIp='" + lastIp + '\'' +
                ", lastDatatime=" + lastDatatime +
                ", area='" + area + '\'' +
                ", userType='" + userType + '\'' +
                ", cominfoId=" + cominfoId +
                ", gmtCreate=" + gmtCreate +
                ", gmtModified=" + gmtModified +
                '}';
    }
}