package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.AuthorityPermission;

import java.util.List;

public interface AuthorityPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_permission
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_permission
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    int insert(AuthorityPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_permission
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    int insertSelective(AuthorityPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_permission
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    AuthorityPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_permission
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    int updateByPrimaryKeySelective(AuthorityPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_permission
     *
     * @mbg.generated Wed Dec 23 19:10:50 CST 2020
     */
    int updateByPrimaryKey(AuthorityPermission record);


    List<Integer> getPermissionIdByAuthorityId(List<Integer> authorityId);
}