package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.Authority;


import java.util.List;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    Authority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Wed Dec 23 20:45:57 CST 2020
     */
    int updateByPrimaryKey(Authority record);

    List<Authority> getAuthorityList(List<Integer> authorityId);
}