package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.Business;

import java.util.List;

public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int insert(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int insertSelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    Business selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int updateByPrimaryKeySelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int updateByPrimaryKey(Business record);

    List<String> selectByComInfoId(Long id);

    int deleteByComInfoId(Long id);
}