package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.ComAuditReport;

public interface ComAuditReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_audit_report
     *
     * @mbg.generated Mon Aug 02 00:16:56 CST 2021
     */
    int insert(ComAuditReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_audit_report
     *
     * @mbg.generated Mon Aug 02 00:16:56 CST 2021
     */
    int insertSelective(ComAuditReport record);
}