package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.ComFillReport;

public interface ComFillReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int insert(ComFillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int insertSelective(ComFillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    ComFillReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int updateByPrimaryKeySelective(ComFillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int updateByPrimaryKey(ComFillReport record);
}