package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.controller.settings.viewObject.UnitFillReportVO;
import com.hyjj.hyjjservice.dataobject.ComFillReport;

import java.util.Date;
import java.util.List;

public interface ComFillReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int insert(ComFillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int insertSelective(ComFillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    ComFillReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int updateByPrimaryKeySelective(ComFillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int updateByPrimaryKey(ComFillReport record);

    List<UnitFillReportVO> selectFillReport(Long id);
    List<UnitFillReportVO> selectNotFillReport(Long id);
    int insertFillReport(Long comInfoId, Integer reportId, Date date);
    List<Integer> selectReportTemplateId(Long id);
    int deleteFillReport(Long comInfoId, Integer reportId);
    int deleteAllFillReport(Long comInfoId);
}