package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.ComFillReport;

public interface ComFillReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Sun Mar 07 15:29:26 CST 2021
     */
    int insert(ComFillReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_fill_report
     *
     * @mbg.generated Sun Mar 07 15:29:26 CST 2021
     */
    int insertSelective(ComFillReport record);
}