package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dao.param.ComInfoQueryPo;
import com.hyjj.hyjjservice.dataobject.ComInfo;
import com.hyjj.hyjjservice.service.company.model.CompanyAnalyseModel;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface ComInfoMapper {


    List<ComInfo> selectByIndustryEtc(ComInfoQueryPo queryPo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    int insert(ComInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    int insertSelective(ComInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    ComInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    int updateByPrimaryKeySelective(ComInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo
     *
     * @mbg.generated Tue Dec 29 16:21:52 CST 2020
     */
    int updateByPrimaryKey(ComInfo record);

    Long selectCountCompany();

    List<CompanyAnalyseModel> countByRegion();

    List<CompanyAnalyseModel> countByIndustry();

    List<CompanyAnalyseModel> countByByComType();

    /**
     * 查询所有单位信息
     * @return
     */
    List<ComInfo> selectAllCompany();

    /**
     * 根据用户id查询公司名称
     * @param userId
     * @return
     */
    String selectCompanyNameByUserId(@Param("userId") Long userId);
}