package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.ComInfoAppendix;
import com.hyjj.hyjjservice.service.company.model.DeatailComInfoModel;

public interface ComInfoAppendixMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo_appendix
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo_appendix
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int insert(ComInfoAppendix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo_appendix
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int insertSelective(ComInfoAppendix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo_appendix
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    ComInfoAppendix selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo_appendix
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int updateByPrimaryKeySelective(ComInfoAppendix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cominfo_appendix
     *
     * @mbg.generated Fri Jan 01 15:29:50 CST 2021
     */
    int updateByPrimaryKey(ComInfoAppendix record);

    DeatailComInfoModel selectDetailByPrimaryKey(Long id);
}