package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.FormFlow;

public interface FormFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_flow
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insert(FormFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_flow
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insertSelective(FormFlow record);
}