package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.Process;

public interface ProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int insert(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int insertSelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    Process selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int updateByPrimaryKeySelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sat Jul 31 13:57:21 CST 2021
     */
    int updateByPrimaryKey(Process record);
}