package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.Process;
import org.apache.ibatis.annotations.Param;

public interface ProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int insert(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int insertSelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    Process selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int updateByPrimaryKeySelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Mon Aug 02 15:56:45 CST 2021
     */
    int updateByPrimaryKey(Process record);

    Process selectByReportId(@Param("reportId") Long reportId);

    int updateProcessByReportId(@Param("reportId") Integer reportId,@Param("process")Process process);
}