package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.Publish;

import java.util.List;

public interface PublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int insert(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int insertSelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    Publish selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int updateByPrimaryKeySelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int updateByPrimaryKey(Publish record);

    List<Publish>  selectPublishOrderByGmtCreate();
}