package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.PublishKeyword;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PublishKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_keyword
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_keyword
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int insert(PublishKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_keyword
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int insertSelective(PublishKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_keyword
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    PublishKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_keyword
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int updateByPrimaryKeySelective(PublishKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_keyword
     *
     * @mbg.generated Sat Jan 09 22:36:47 CST 2021
     */
    int updateByPrimaryKey(PublishKeyword record);

    int insertBatch(List<PublishKeyword> list);
}