package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.controller.settings.viewObject.ReportNameAndIdVO;
import com.hyjj.hyjjservice.controller.settings.viewObject.ReportTemplateInfoVO;
import com.hyjj.hyjjservice.controller.settings.viewObject.ReportTemplateVO;
import com.hyjj.hyjjservice.controller.settings.viewObject.SearchReportTemplateVO;
import com.hyjj.hyjjservice.dataobject.ReportData;
import com.hyjj.hyjjservice.dataobject.ReportTemplate;
import io.swagger.models.auth.In;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface ReportTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    int insert(ReportTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    int insertSelective(ReportTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    ReportTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    int updateByPrimaryKeySelective(ReportTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_template
     *
     * @mbg.generated Sat Jan 09 22:49:25 CST 2021
     */
    int updateByPrimaryKey(ReportTemplate record);

    List<String> getReportNumber(@Param("reportTemplateIds") List<Long> reportTemplateIds);

    List<ReportTemplateVO> getReportTemplateList(@Param("reportTemplateVO") ReportTemplateVO reportTemplateVO);

    ReportTemplateInfoVO getReportTemplateInfo(Integer id);
    List<ReportNameAndIdVO> selectReportNameAndId();
    ReportTemplate getRowAndColByTemplateId(Integer reportId);

    int getReportTemplateListSum(@Param("reportTemplateVO") ReportTemplateVO reportTemplateVO);

    @Update("UPDATE report_template SET head_html = #{head}, body_html = #{body}, tail_html = #{tail} WHERE title = #{name}")
    void upload(String name,String head, String body, String tail);

    ReportTemplate getAllValueRowAndCol(Integer reportId);
}