package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.ReportDataRow;

public interface ReportDataRowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data_row
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data_row
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insert(ReportDataRow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data_row
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insertSelective(ReportDataRow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data_row
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    ReportDataRow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data_row
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKeySelective(ReportDataRow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_data_row
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKey(ReportDataRow record);
}