package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.StatisticsTargetKey;

public interface StatisticsTargetKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_target_key
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insert(StatisticsTargetKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_target_key
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insertSelective(StatisticsTargetKey record);
}