package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.TargetKeyValue;

public interface TargetKeyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insert(TargetKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insertSelective(TargetKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    TargetKeyValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKeySelective(TargetKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKey(TargetKeyValue record);
}