package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.TargetValue;

public interface TargetValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insert(TargetValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insertSelective(TargetValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    TargetValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKeySelective(TargetValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKey(TargetValue record);
}