package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.controller.statistic.viewObject.StatisticVo;
import com.hyjj.hyjjservice.dataobject.TargetKeyValue;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TargetKeyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insert(TargetKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insertSelective(TargetKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    TargetKeyValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKeySelective(TargetKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_key_value
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKey(TargetKeyValue record);



    List<StatisticVo> getStatisticInfoById(@Param("years") List<Integer> years,
                                       @Param("areaName") String areaName,
                                       @Param("targetId") Long targetId);

    List<StatisticVo> getStatisticInfoByIds(@Param("years") List<Integer> years,
                                           @Param("areaName") String areaName,
                                           @Param("targetIds") List<Long> targetIds);
}