package com.hyjj.hyjjservice.dao;

import com.hyjj.hyjjservice.dataobject.UrgeData;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UrgeDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urge_data
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urge_data
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insert(UrgeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urge_data
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int insertSelective(UrgeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urge_data
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    UrgeData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urge_data
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKeySelective(UrgeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urge_data
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(UrgeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urge_data
     *
     * @mbg.generated Wed Dec 16 22:56:19 CST 2020
     */
    int updateByPrimaryKey(UrgeData record);

    /**
     * 搜索指定年份和公司的催办名单
     * @param preYear
     * @param nextYear
     * @param company
     * @return
     */
    UrgeData selectUrgeDataByYearAndCompanyName(@Param("preYear") String preYear,
                                                @Param("nextYear") String nextYear,
                                                @Param("company") String company);

    List<UrgeData> getUrgeData(@Param("userId") Long userId);

    int updateByPrimaryKeysSelective(@Param("ids") List<Long> ids);
}